apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::773211281954:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CZPTLCFLLZXO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::773211281954:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-15T16:39:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-15T16:39:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1485"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b279c682-33f4-4d92-ab55-dd720fc72cb5
